version: "3.7"

services:
  django:
    build: .
    restart: always
    expose:
      - "8000"
    volumes:
      - ./project:/code
    command: gunicorn -w 3 djangoproject.wsgi:application --bind 0.0.0.0:8000
    networks:
      - django-network
    env_file: django.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data/
    networks:
      - django-network
    env_file: db.env

  nginx:
    image: nginx:alpine
    restart: always
    expose:
      - "80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./project/staticfiles:/code/staticfiles
      - ./project/media:/code/media
    networks:
      - django-network
      - traefik-network
    depends_on:
      - django
    labels:
      - "traefik.enable=true"
      - "traefik.backend=web"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:calendar4friends.ddnss.de"
      - "traefik.docker.network=proxy_traefik-network"

networks:
  django-network:
    driver: bridge
  traefik-network:
    external: true
    name: proxy_traefik-network
